services:
  joomla:
    image: "joomla:latest"
    volumes:
      - "joomla_data:/var/www/html"
    environment:
      - SERVICE_FQDN_JOOMLA
      - JOOMLA_DB_HOST=mariadb
      - "JOOMLA_DB_USER=${SERVICE_USER_JOOMLA}"
      - "JOOMLA_DB_PASSWORD=${SERVICE_PASSWORD_JOOMLA}"
      - "JOOMLA_DB_NAME=${MYSQL_DATABASE:-joomla-db}"
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://127.0.0.1"
      interval: 2s
      timeout: 10s
      retries: 10
